name: Deploy bucketRequest

on: push

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bucketrequest-pubsub

    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        run: |
          gcloud functions deploy bucketRequest \
            --trigger-topic bucket-request \
            --region=us-east4 \
            --runtime=nodejs12 \
            --memory=128MB
