name: Deploy sendToTask

on: push

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sendtotask-pubsub

    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VALIDATOR_URL: ${{ secrets.VALIDATOR_URL }}
          GCP_SA_EMAIL: ${{ secrets.GCP_SA_EMAIL }}
        run: |
          gcloud functions deploy sendToTask \
            --trigger-events providers/cloud.firestore/eventTypes/document.update \
            --trigger-resource "projects/$PROJECT_ID/databases/(default)/documents/buckets/{bucketName}"
            --region=us-east4 \
            --runtime=nodejs12 \
            --memory=128MB \
            --set-env-vars PROJECT_ID="$PROJECT_ID",VALIDATOR_URL="$VALIDATOR_URL",GCP_SA_EMAIL="$GCP_SA_EMAIL"
