name: Deploy sendToTask

on: push

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sendtotask-http

    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud functions deploy sendToTask \
            --trigger-http \
            --region=us-east4 \
            --runtime=nodejs12 \
            --memory=128MB \
            --set-env-vars PROJECT_ID="$PROJECT_ID"
